### ISSUE TITLE
Identifying sites as test/control

### ISSUE THREAD

**Issue by annamoore1978** [RudolfCardinal/ithrive_data_extractor#2]
Would it be possible to add a table/mechanism that determines if a site is a test(ithrive) or a control?

**_ithrive sites_**
Bexley
Cambs & Peterborough
Camden
Hertfordshire
Luton
Manchester_salford
Stockport
Tower Hamlets
waltham Forest
Warrington

**_Controls_**
Bradford
Suffolk
Lewisham
Nene & Corby/Northants
Norfolk
Portsmouth
Southampton
Stoke
Sunderland
Worcester

**Comment by RudolfCardinal** [comment]
Added via ``site.is_ithrive_site`` column, via https://github.com/RudolfCardinal/ithrive_data_extractor/commit/1a11d27b0d1710ea6c234459fe4e0f0199ab88b3
