### ISSUE TITLE
Cleaning Contact Types

### ISSUE THREAD

**Issue by annamoore1978** [RudolfCardinal/ithrive_data_extractor#3]
Contact type is a mix of methods of contact (eg email/ phone/F2F) and appointment types (eg CPA/ assessment). 
Contact how appears to have all the methods (f2f/email). GIven this, I think we should probably take that info out of contact type, if possible.

**Comment by RudolfCardinal** [comment]
This is a raw source text field (``contact.type``) so full of considerable variation. Suspect this is the same issue, really, as https://github.com/RudolfCardinal/ithrive_data_extractor/issues/5 .
